#!/bin/bash

API_URL="http://127.0.0.1:8000/api/pdfConvert"
PDF_FILE_PATH="Oladele Usman  - Resume.pdf"
TOKEN="your_bearer_token_here"  

# Simple test request with UTF-8 header and Authorization
curl -X POST "$API_URL" \
    -H "Content-Type: multipart/form-data; charset=utf-8" \
    -H "Authorization: Bearer $TOKEN" \
    -F "pdf=@$PDF_FILE_PATH" \
    -F "from_page=1" \
    -F "to_page=4" \
    -F "theme=modern" \
    -F "summary_type=short" | jq